# Generated by Django 5.2.7 on 2026-01-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('passed_year', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('course_interested', models.CharField(max_length=100)),
                ('timings', models.JSONField()),
                ('training_method', models.JSONField()),
                ('training_mode', models.JSONField()),
                ('source', models.CharField(max_length=100)),
                ('demo_given_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
