# Generated by Django 5.2.7 on 2026-01-29 06:52

import loginpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpp', '0003_contactenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=10)),
                ('alternate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('passed_out_year', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('housewife', 'Housewife')], max_length=20)),
                ('training_mode', models.JSONField()),
                ('training_method', models.JSONField()),
                ('timings', models.JSONField()),
                ('date_of_joining', models.DateField()),
                ('demo_given_by', models.CharField(max_length=100)),
                ('allocated_to', models.CharField(max_length=100)),
                ('admission_by', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admissions/', validators=[loginpp.models.validate_image_size])),
                ('fee_once_paid_not_refundable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
