# Generated by Django 5.2.7 on 2026-02-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpp', '0005_onlineenquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineenquiry',
            name='status',
            field=models.CharField(choices=[('demo_pending', 'Demo Pending'), ('demo_completed', 'Demo Completed'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='demo_pending', max_length=20),
        ),
    ]
